### ISSUE TITLE
Console is spammed with an error message (1.14.4 - Paper)

### ISSUE THREAD

**Issue by FamiliarGecko** [hornta/racing#16]
I was testing the plugin. I created a race, and when I started it I recived an error message in the chat, and the console started to be spammed with this error message: https://hatebin.com/qqyrzvyeyk

Apart from this, the race was otherwise working fine.

Paper version: 1.14.4 - 167

**Comment by hornta** [comment]
I suspect you are not using the correct version of ProtocolLib. I've marked the version I use:
![image](https://user-images.githubusercontent.com/4553604/63052437-9d722a00-bedf-11e9-9465-ce742c972e62.png)

**Comment by FamiliarGecko** [comment]
Yeah, this was the problem... turns out I'm an idiot... ._.

I don't know how I managed to miss that, scince I've read through ProtocolLib's page before downloading it...

Anyhow, thanks for the quick response, and sorry for bothering you!
