### ISSUE TITLE
restore players when they finish race

### ISSUE THREAD

**Issue by hornta** [hornta/racing#20]
players should be restored when the player finished the race, not when the race ends.

**Comment by cyberkeiler** [comment]
This should also resolve #13. Top!

**Comment by hornta** [comment]
I'm not sure this will resolve #13. By "restoring" a player it means giving them their inventory, health, hunger, etc.. basically restoring them to their state before the race started(not restoring to their old position though).
#13 I think will need to be actively disabled.

**Comment by hornta** [comment]
Fixed in 1.19.0
