### ISSUE TITLE
Suggestion: Commands on start

### ISSUE THREAD

**Issue by larssieboy18** [hornta/racing#23]
Hello,

It would be very nice to include a config option that allows us to set certain commands on start, for example: /feed, /fly disable or /heal.

Best regards,
Lars

**Comment by hornta** [comment]
Are these the commands you want to execute before start? Because Racing will make sure they are properly fed, and gamemode is changed to adventure(no fly) and health is maxed out.

**Comment by larssieboy18** [comment]
Yeah before start. I thought of it because I only had 3 hunger bars left, which meant I couldn’t sprint on start of the race

**Comment by hornta** [comment]
it should have been given you full health. Maybe it didn't do that because of the error you posted in your other issue?

**Comment by larssieboy18** [comment]
Maybe then be able to give commands when the race ends? For example: people get placed into spectator mode so they can watch the others

**Comment by hornta** [comment]
Ok, yes I believe that shouldn't be a default feature but I can add the option to have commands be executed before a race begins and when it ends.

**Comment by hornta** [comment]
@larssieboy18 Check the latest version 1.21.0 with support for this.
