### ISSUE TITLE
Start race by joining

### ISSUE THREAD

**Issue by GnaXi** [hornta/racing#28]
Hi,

It would be awesome, if this plugin could be used without the assistance of an admin.
Lets say that 2 players would like to race, I am forced to be online as and admin to start the race.
Instead, let them right click the sign to start the race themselves, without me having to go in there and use the /rc start {race} command.

This would make the plugin able to act as a mini game without admin interaction.

**Comment by GnaXi** [comment]
Well, I should probably have taken a closer look in the config file, as the feature is already there. Sorry! :)

**Comment by hornta** [comment]
@GnaXi Hi. Yes this feature was added in the last version, but there is a small bug which is going to be fixed in the next version.
