### ISSUE TITLE
License

### ISSUE THREAD

**Issue by TheMolkaPL** [hornta/racing#43]
What's the license of this project?

**Comment by hornta** [comment]
Hi.
https://choosealicense.com/licenses/gpl-3.0/
I should add the license file to the repo. Do you wish you wish to contribute?

**Comment by TheMolkaPL** [comment]
> Do you wish you wish to contribute?

Yes, thanks! I've sent you a pull request.

I'll keep this open until you put a license file in the repo.

**Comment by hornta** [comment]
That's nice :) I added a LICENSE file so I'm closing.
