### ISSUE TITLE
Rewards for participating

### ISSUE THREAD

**Issue by philipkoivunen** [hornta/racing#5]
Make it configurable to hand out rewards for races

**Comment by philipkoivunen** [comment]
Rewards should be configurable and it should be configurable so you can hand out rewards for different achivements.

Achivements that can be used in config:
- Firstplace, second place... 
- On completion
- Beats personal record in the _/rc top_ list(not for wins)
- Beats record in _/rc top_ list (not for wins)

RewardTypes:
- Economy money
- A command that runs (for example /give)

**Comment by hornta** [comment]
fixed in 1.21.0. not fixed for beating personal records since it would open up to abuse.
